# Site settings
name: G403
email: your-email@domain.com
description: A website for awesome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://g403.co" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Includes an icon in the footer for each user name you enter
links:
  github: gabriel403
  twitter: gabriel403
  email: me@g403.co

# Build settings
markdown: kramdown
permalink: /:title/

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed
